### ISSUE TITLE
ameba_d_tools, please support MacOS and Linux

### ISSUE THREAD

**Issue by Pillar1989** [ambiot/ambd_arduino#1]
I believe that 80% of individual developers are using MacOS and Linux. Please provide as soon as possible. We really don't want to use Windows at home.

**Comment by technoblogy** [comment]
I'm on MacOS and would also be interested in exploring the Ameba boards with the Arduino IDE.

**Comment by ambiot** [comment]
I am working on supporting both MacOS and Linux. The tools will be released soon.

**Comment by technoblogy** [comment]
Great! I'll be happy to beta test it and provide feedback - what board would you recommend?

**Comment by technoblogy** [comment]
Why have you closed this? Is the MacOS support now available? What about my question:

> Great! I'll be happy to beta test it and provide feedback - what board would you recommend?

**Comment by Pillar1989** [comment]
It's been tested. Perfect support.You can try it. @technoblogy

**Comment by technoblogy** [comment]
I get:

    Error downloading https://github.com/ambiot/ambd_arduino/raw/master/Arduino_package/package_realtek.com_amebad_index.js

**Comment by Pillar1989** [comment]
Looks like GitHub has a grudge against you and won't let you download it.

**Comment by technoblogy** [comment]
Sorry, my bad - I had left the "on" off the end of .json because in my browser it had wrapped onto the next line. Works now.
