### ISSUE TITLE
WiFiAPMode example tied to firmware version

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#10]
The Access Point example **WiFiAPMode.ino** contains the test:
````
    String fv = WiFi.firmwareVersion();
    if (fv != "1.0.0") {
        Serial.println("Please upgrade the firmware");
    }
````
This seems dangerous, since it will stop working if you update the firmware to, for example, 1.1.0.

**Comment by ambiot** [comment]
We will discuss removing this section for the next release.

**Comment by ambiot** [comment]
The latest version v3.0.6 has removed the section.
