### ISSUE TITLE
Does this library support BW15-kit (RTL8720CF)?

### ISSUE THREAD

**Issue by jiangyi1985** [ambiot/ambd_arduino#102]
I have an Ai-thinker NodeMCU bw15-kit.

Specification:
https://docs.ai-thinker.com/_media/rtl8710/bw15-kit_v1.0%E8%A7%84%E6%A0%BC%E4%B9%A6.pdf

Same sample online:
https://www.aliexpress.com/item/1005003730851266.html

I set the jump wire to PROG and try to upload. But 
![image](https://user-images.githubusercontent.com/11713383/180658853-38415807-f8b4-478b-952f-4a8816d90582.png)

I also tried pressing RESET button while holding BURN button. Still the same.

My settings:
![image](https://user-images.githubusercontent.com/11713383/180658859-296567ae-700a-4b2f-a5b3-1f4f8ef883cf.png)

**Comment by xidameng** [comment]
@jiangyi1985 Hi, BW15 or RTL8720CF belongs to the Ameba Z2 family, thus is **NOT** supported with Ameba D Arduino SDK, more details see here
https://www.amebaiot.com/en/amebaz2/
