### ISSUE TITLE
Creating a Wi-Fi Soft Access Point options

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#12]
A couple of other questions:

- Is there a call to disconnect a Soft Access Point. On the ESP8266/32 it's:

      WiFi.softAPdisconnect(true);

- Is there a call to create a hidden Soft Access Point? On the ESP8266/32 there's an optional fourth parameter:

      bool hidden = true;
      WiFi.softAP(ssid, pass, channel, hidden);

I've had a look in the source but can't find anything.
Thanks, David

**Comment by Aurical** [comment]
- `WiFi.disconnect()` should disable the AP mode

- It looks like hidden SSID ap mode is not exposed in the Arduino facing API by default. The functionality is present in `wifi_conf.h` file, with the `wifi_start_ap_with_hidden_ssid` function. It should be possible to link this function into `wifi_drv.cpp` and implement hidden SSID ap mode in `WiFI.cpp`

**Comment by ambiot** [comment]
The latest version v3.0.6 has added the hidden SSID function.
