### ISSUE TITLE
RTL8720DN not working with BMP280 arduino lbrary

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambd_arduino#132]
[BMP280 arduino library ](https://www.arduino.cc/reference/en/libraries/adafruit-bmp280-library/) works well with ESP32,
but RTL8720DN did not work.

[https://github.com/adafruit/Adafruit_BMP280_Library](https://github.com/adafruit/Adafruit_BMP280_Library)

[Adafruit_BMP280.cpp](https://github.com/adafruit/Adafruit_BMP280_Library/blob/master/Adafruit_BMP280.cpp)
is it because RTL8720 i2c driver not compatible ? any fix ?

**Comment by xidameng** [comment]
Hi @rkuo2000 

Could you elaborate more on how "but RTL8720DN did not work." ?

I have compiled and run the example provided in this library, and both I2C and SPI mode seems to be working

**Comment by rkuo2000** [comment]
Not sure why all my BMP280 not working with Adafruit BMP280 library, even using ESP32.
However, I verify BMP085, here's the status:

Board: RTL8720DN
Sensor: BMP085
IDE: Arduino 2.0.0
Library: Adafruit BMP085 
Status: works fine.
