### ISSUE TITLE
RTL8720DN supporting PS4 controller driver

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambd_arduino#133]
Here's a PS4 controller driver for ESP32
[https://github.com/aed3/PS4-esp32](https://github.com/aed3/PS4-esp32)

For RTL8720DN, how to modify the following two ?
[ps4_l2cap.c](https://github.com/aed3/PS4-esp32/blob/master/src/ps4_l2cap.c)  
[ps4_spp.c](https://github.com/aed3/PS4-esp32/blob/master/src/ps4_spp.c)

**Comment by xidameng** [comment]
Hi @rkuo2000 

This library is heavily dependent on the `esp-idf` bluetooth libraries, not on the unified Arduino Bluetooth API, thus supporting 
 this library means porting and re-writing almost the entirety of this library...  

Thus , this feature is currently not supported.

However, we do feel adding support for a PS controller is good idea for our users. Therefore, if you would help to initiate this effort, we would also love to provide supports along the way 😃

**Comment by rkuo2000** [comment]
Hi, 
Yes, PS4 controller is very useful to remote control Robots, especially Drones (Quadcopter, ...).
It seems to me, ps4_spp.c and ps4_l2cap.c need to be created,
but I don't have the knowledge of your bluetooth stack to write those codes.
