### ISSUE TITLE
WPA2 Enterprise WIFI support

### ISSUE THREAD

**Issue by AQIBRIAZ** [ambiot/ambd_arduino#140]
Hi,

Can you let me know how to connect Enterprise wifi? is it supported or not?

Thanks and Regards

**Comment by S10143806H** [comment]
Hi, 
The WPA2 function is supported at the Wi-Fi driver level. For testing WPA2 mode, you might need to configure your associated AP with the security of WPA2-PSK TKIP, WPA2-PSK AES, or WPA2-PSK TKIP&AES mixed mode. To ensure the WPA2 mode is working, make sure your PC and Ameba board connect to the same AP and perform a ping test.
Thanks

**Comment by AQIBRIAZ** [comment]
Hi,

WPA2 personal is working fine. I am trying to connect to WPA2 Enterprise network. It required additional parameters and certificate .

Does this arduino sdk support the enterprise network ?

Regards

**Comment by M-ichae-l** [comment]
@AQIBRIAZ , please refer to https://github.com/ambiot/ambd_sdk/releases/tag/v1.0.1, Arduino SDK not support EAP.
