### ISSUE TITLE
is it compatible with RTL8720DN?

### ISSUE THREAD

**Issue by bkrajendra** [ambiot/ambd_arduino#15]
is it compatible with RTL8720DN mocule?

**Comment by xidameng** [comment]
Check out this repo for RTL8720DN
https://github.com/xidameng/ambd_arduino

**Comment by bkrajendra** [comment]
Thank you for your quick reply. I'll look into it.

**Comment by bkrajendra** [comment]
I have also found this repo with more ported libraries and information for RTL8720DN
https://github.com/mikey60/BW16-RTL8720DN-Module-Arduino

**Comment by xidameng** [comment]
> I have also found this repo with more example sketches and information for RTL8720DN
> https://github.com/mikey60/BW16-RTL8720DN-Module-Arduino

Thanks for the info~ Hope you find the RTL8720DN handy to use, if you do enjoy, you may consider fork the repo and contribute yourself~

**Comment by bkrajendra** [comment]
Yes definitely!
