### ISSUE TITLE
OTA Updates

### ISSUE THREAD

**Issue by mikey60** [ambiot/ambd_arduino#16]
Is there a way to do Over-The-Air (OTA) updates using WiFi?

**Comment by xidameng** [comment]
Hi, this feature has not yet supported on Arduino IDE, but if you are interested, you may check out the ambd_sdk repo under this same account and the OTA example over there at https://github.com/ambiot/ambd_sdk/tree/master/component/common/example/ota_http

**Comment by ambiot** [comment]
Plan to support this function in the future after we release V3.0.8

**Comment by jdt1** [comment]
> Plan to support this function in the next release.

Is there any progress on this function?

**Comment by M-ichae-l** [comment]
@jdt1  it is ongoing. Windows is ready, we are working on linux and macos.

**Comment by jdt1** [comment]
> @jdt1 it is ongoing. Windows is ready, we are working on linux and macos.

If Windows is ready, can I download it already?

**Comment by M-ichae-l** [comment]
> 

the PR is ready but has conflicts with master. I will inform the PR holder to update. Then apply to merge.

**Comment by S10143806H** [comment]
> > @jdt1 it is ongoing. Windows is ready, we are working on linux and macos.
> 
> If Windows is ready, can I download it already?

Hi @jdt1,

Thanks for your waiting. 

The current OTA tool is compatible with the latest AmebaD Arduino SDK. However, I am still working on the tool executable for macOS and Linux.  

I will update the PR once everything is done. Meanwhile, all the conflicts will be solved.

**Comment by M-ichae-l** [comment]
Closed as the feature already supported.
