### ISSUE TITLE
如何将8720DN 配置为5GHz频段下的AP

### ISSUE THREAD

**Issue by songzhishuo** [ambiot/ambd_arduino#181]
Arduino 默认的API 是将wiif 配置为2.4Ghz的AP，能否提供API或者接口使用5G频段。
是否有方式同时产生2.4G和5G双频段的AP

**Comment by S10143806H** [comment]
Hi @songzhishuo,
目前的Arduino SDK 并沒有提供使用 AP模式下使用5G頻段的API接口，默認產生都是 2.4GHz 頻段的 AP。
謝謝

**Comment by S10143806H** [comment]
Hi @songzhishuo,
因爲您在 AmebaIoT 論壇上有 [相同的提問](https://forum.amebaiot.com/t/8720dn-5ghz-ap-181/2013)，所以我會先關掉這個 GitHub Issue. 後續的問題討論可以在論壇上進行。
謝謝
