### ISSUE TITLE
Make use of DCT API?

### ISSUE THREAD

**Issue by vshymanskyy** [ambiot/ambd_arduino#195]
I need to store some settings in the form of key-value pairs in the NVM (Flash).
Overall, I'm trying to get support for Ameba devices for my [Preferences library](https://github.com/vshymanskyy/Preferences).

One option I found is to use DCT:
```cpp
// initial DCT
ret = dct_init(DCT_BEGIN_ADDR, MODULE_NUM, VARIABLE_NAME_SIZE, VARIABLE_VALUE_SIZE, 1, 0);
// register module
ret = dct_register_module(example_dct_module);
// open module
ret = dct_open_module(&dct_handle, example_dct_module);
```
However, looks like the DCT library is not linked, I'm getting:
```log
undefined reference to `dct_init(unsigned long, unsigned short, unsigned short, unsigned short, unsigned char, unsigned char)'
collect2: error: ld returned 1 exit status
```

Another option is to use some kind of a File system (I see FATFS, but can it be used on the system flash?).

Also, to store any data in the flash, I need to define a dedicated region / partition in the flash memory.
What's the best practice to do that?

@xidameng please advise

**Comment by vshymanskyy** [comment]
Weird, i see that `variants/common_libs/lib_dct.a` gets linked, but still looks like it lacks the relevant functions.

**Comment by vshymanskyy** [comment]
I overlooked the "C" linkage. It builds successfully like this:
```
extern "C" {
  #include <dct.h>
}
```

I also had to add `"-I{ameba.sdkpath}/component/common/file_system/dct"` to the `compiler.ameba.c.include` in `platform.txt`. It would be great if it was included by default.

Didn't test It yet. I need to define a dedicated region / partition in the flash memory.

**Comment by vshymanskyy** [comment]
So yeah, `DCT` actually works as a back-end for the Preferences library:
```log
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:142:test_bytes:PASS
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:144:test_zero_bytes:PASS
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:146:test_utf8_key:PASS
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:147:test_utf8_value:PASS
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:148:test_remove_key:PASS
/home/vshymanskyy/Arduino/Preferences_Test/Preferences_Test.ino:149:test_clear_namespace:PASS
```

**Comment by vshymanskyy** [comment]
So, there are 2 questions left:
- `"-I{ameba.sdkpath}/component/common/file_system/dct"` needs to be added to `compiler.ameba.c.include` in `platform.txt`.
- I need to define the flash region for the DCT. I noticed that DCT only requires the start address during initialization, the size is not specified explicitly. What's the best practice to configure the DCT?

**Comment by S10143806H** [comment]
@vshymanskyy ,

The dct function is default wrapped in `lib_dct.a` under `/variants/common_libs/`, therefore, to compile dct successfully, you may add in `"-I{ameba.sdkpath}/component/common/file_system/dct"` in `platform.txt` Line 72.

For the DCT configuration, please refer to our standard sdk example located at `ambd_sdk\component\common\example\dct`. (https://github.com/ambiot/ambd_sdk/tree/dev/component/common/example/dct)

Thank you.

**Comment by vshymanskyy** [comment]
The `Device Configuration Table` support was added and pushed to GitHub.
@S10143806H would you consider this:
1. Adding the required include path to the `platform.txt`
2. Adding the Preferneces library to your library package by default? https://github.com/vshymanskyy/Preferences

**Comment by M-ichae-l** [comment]
@vshymanskyy 
Thanks for bring it out. As we have discovered, there is no example our any API for DCT demo at arduino level `Arduino_package/hardware/libraries`

But there is a `lib_dct.a ` at compilations process. So as you have provided the [Preference](https://github.com/vshymanskyy/Preferences). Why not just do the Pull Request, as a submodule of the SDK? 

- you can still maintain your own code at your repo
- it can be a part of the Ambd_arduino SDK

**Comment by S10143806H** [comment]
> The `Device Configuration Table` support was added and pushed to GitHub. @S10143806H would you consider this:
> 
> 1. Adding the required include path to the `platform.txt`
> 2. Adding the Preferneces library to your library package by default? https://github.com/vshymanskyy/Preferences

Hi @vshymanskyy ,
Sorry for the late reply.
- Could you please define what is `Device Configuration Table` referring to? I could not find any related code in your repo. Thanks

1. As answered previously, the line including `lib_dct.a` have exited in `platform.txt`: https://github.com/ambiot/ambd_arduino/blob/8e9512a7ac1372b6cc123127da36324f8d0002a2/Arduino_package/hardware/platform.txt#L83C1-L83C1

3. Yes, you could go ahead with Pull Request your examples into our SDK upon verification. I have tested your examples but both of them seems could not compile successfully in AmebaD Arduino environment.
![image](https://github.com/ambiot/ambd_arduino/assets/9852678/6b210c44-d375-4e84-bbfc-2451fba6d1a7)
![image](https://github.com/ambiot/ambd_arduino/assets/9852678/c1589638-696d-4cf0-a4d6-a5c244d7e132)

Therefore, maybe could you please clarify what are things that I could do to help you with your Pull Request contribution. And we could proceed to review your codes. Thank you.

**Comment by vshymanskyy** [comment]
- DCT is short for `Device Configuration Table`, as far as I understand. The related parts of the library are highlighted here: https://github.com/ambiot/ambd_arduino/issues/195#issuecomment-1669594923
- Yes, `lib_dct.a` is linked, but `component/common/file_system/dct` is not included by default: https://github.com/ambiot/ambd_arduino/blob/8e9512a7ac1372b6cc123127da36324f8d0002a2/Arduino_package/hardware/platform.txt#L72
- As for the examples, looks like you're using the released version of `Preferences`, but you need to use the latest (unreleased) version from github. The default examples are using `Serial.printf` which is not available on `Amebad`. We can improve it either by changing the examples or by adding `Serial.printf` to your platform.

**Comment by vshymanskyy** [comment]
Updated one of the examples so it doesn't rely on `Print::printf()`: https://github.com/vshymanskyy/Preferences/blob/main/examples/StartCounter/StartCounter.ino

**Comment by vshymanskyy** [comment]
will get to it soon

**Comment by vshymanskyy** [comment]
still not there;) sorry!

**Comment by M-ichae-l** [comment]
@vshymanskyy 
Thanks for the patient, I have create a submoule of your repo main branch. #5a4b8b79ede9ec2502da29b34cd89e65749bfad6
You may want to review the update. If any update or debug I will help to merge.

**Comment by vshymanskyy** [comment]
I'm alive!

**Comment by M-ichae-l** [comment]
@vshymanskyy  
Could you review about the submodule system for the example you have ported?

**Comment by vshymanskyy** [comment]
@M-ichae-l please elaborate, Didn't get your question

**Comment by vshymanskyy** [comment]
@M-ichae-l ?

**Comment by M-ichae-l** [comment]
@vshymanskyy 
Can you review the submodule here [https://github.com/ambiot/ambd_arduino/tree/dev/Arduino_package/hardware/libraries](https://github.com/ambiot/ambd_arduino/tree/dev/Arduino_package/hardware/libraries)
![2024-1-23_16-1-31](https://github.com/ambiot/ambd_arduino/assets/35476432/84fa0601-9e9a-4a60-8d41-56da30d346c5)

**Comment by vshymanskyy** [comment]
ok, i should be able to verify it furing the weekend.
sorry for a delay, the project that used  it was put on hold, so i need to setup the environment again.
this holds back any progress

**Comment by vshymanskyy** [comment]
Looks like everything is correct. Closing the ticket.
Thanks for all your help and support!
