### ISSUE TITLE
Pinout LED blue (BW16 RTL8720DN)

### ISSUE THREAD

**Issue by rstephan** [ambiot/ambd_arduino#197]
The pinout on the BW16 RTL8720DN is mixed up.
The Fritzing and SVG images show the wrong pin.
LED B is connected to pin 11 not 1.

As seen here in the table below the image
https://www.amebaiot.com/en/amebad-bw16-arduino-getting-started/

**Comment by M-ichae-l** [comment]
@rstephan please refer to [#](https://github.com/ambiot/ambd_arduino/commit/951cb71aa9d3ac1a74ca105e6bd17f556b4c8d4f) for the fix.

**Comment by rstephan** [comment]
Thanks
