### ISSUE TITLE
mDNS service discovery

### ISSUE THREAD

**Issue by vladkozlov69** [ambiot/ambd_arduino#198]
Is there a way to perform mDNS service discovery using current API implementation?

**Comment by M-ichae-l** [comment]
https://www.amebaiot.com/en/amebad-arduino-mdns-basic/

**Comment by vladkozlov69** [comment]
Thanks @M-ichae-l , I have seen this article, here the Arduino IDE performs mDNS search to find Amebad board - but what I want is the opposite case: to perform mDNS lookup on Ameba side to find for example, MQTT server in local network. I know that I need to join Ameba network interface to multicast group to listen to the mDNS responses, and send mDNS queries to multicast address - but maybe there is a ready-to-use API in Realtek code?

**Comment by vladkozlov69** [comment]
I have ended up creating a library for AmebaD, based on some ESP8266 code: https://github.com/vladkozlov69/RTL8720DN_mdns
