### ISSUE TITLE
[MicroPython feature request] WiFi scan improve.

### ISSUE THREAD

**Issue by water5** [ambiot/ambd_arduino#200]
```python
wifi = WLAN(mode = WLAN.STA)
wifi.scan()
```

MicroPython Ameba port, WiFi scan result type is 'NoneType', that not easy to access, `list` type is good choice. and sometimes, `channel (or frequency)`, `hidden` item is useful, Ameba port have not that currently.

[https://docs.micropython.org/en/latest/library/network.html#network.AbstractNIC.scan](https://docs.micropython.org/en/latest/library/network.html#network.AbstractNIC.scan)

By the way, please enable [MicroPython repository](https://github.com/ambiot/micropython/tree/ameba)'s `Issues` feature.

**Comment by M-ichae-l** [comment]
@water5  thanks for the first post. You may find the follow link for MicroPython issue page. 
https://github.com/ambiot/ambd_micropython/issues

**Comment by water5** [comment]
@M-ichae-l Thanks.
