### ISSUE TITLE
Compatibility issue: AMB26(RTL8720DF) and NORA-W30(RTL8720DF) share same #defined(BOARD_RTL8720DF).

### ISSUE THREAD

**Issue by LishenTung** [ambiot/ambd_arduino#204]
Hi,
Board AMB25/AMB26 (RTL8720DF) and u-blox NORA-W30 series (RTL8720DF) use the same #defined(BOARD_RTL8720DF). It will make Compatibility issue. please help to solve it. 

Thanks,
Lishen

**Comment by M-ichae-l** [comment]
@LishenTung  We are planning to add unique marco for each board. Please wait for the next release. You can refer to the current temp update here https://github.com/ambiot/ambd_arduino/commit/c1d4a7aecf33da0b58f7c99bcfd34eb2c946b113

**Comment by M-ichae-l** [comment]
Please refer to this version https://github.com/ambiot/ambd_arduino/releases/tag/V3.1.7-QC-V06
