### ISSUE TITLE
Permission denied when compiling on Linux

### ISSUE THREAD

**Issue by IamPhytan** [ambiot/ambd_arduino#208]
Hello,

when compiling a simple Blink sketch for RTL8720DN, I have the following error

```
fork/exec /home/user/.arduino15/packages/realtek/tools/ameba_d_tools/1.1.2/postbuild_img2_arduino_linux: permission denied
```

It seems that some files doesn't have the right permissions when they are installed with the Arduino IDE board manager.

**Comment by S10143806H** [comment]
Hello,
Please refer to the link here for FAQ: 
https://forum.amebaiot.com/t/ubuntu-linux-environment/2259
![image](https://github.com/ambiot/ambd_arduino/assets/9852678/e28780eb-66b8-47fa-88f0-0f5efdd8f29d)
