### ISSUE TITLE
RTL8720DN pinmap wrong for Blue and Green LED pin name

### ISSUE THREAD

**Issue by M-ichae-l** [ambiot/ambd_arduino#21]
for [https://github.com/ambiot/ambd_arduino/blob/master/Ameba_misc/Ameba_Fritzing%20%26%20Pinmux/RTL8720DN(BW16)/graphics/Rtlduino%20pinmap%20LED.svg](https://github.com/ambiot/ambd_arduino/blob/master/Ameba_misc/Ameba_Fritzing%20%26%20Pinmux/RTL8720DN(BW16)/graphics/Rtlduino%20pinmap%20LED.svg)

- Blue should be PA13
- Green should be PA14

**Comment by M-ichae-l** [comment]
following the PR [https://github.com/ambiot/ambd_arduino/pull/24](https://github.com/ambiot/ambd_arduino/pull/24)

**Comment by ambiot** [comment]
Refer to #25 for the fix.
