### ISSUE TITLE
Compile fails on Windows if space exists in path (eg username)

### ISSUE THREAD

**Issue by xixiha5230** [ambiot/ambd_arduino#212]
### Issue Description:

I encountered an error while working with the [ambd_arduino](https://github.com/ambiot/ambd_arduino) project, similar to [this reported issue](https://github.com/ambiot/ambd_arduino/issues/62). Although a suggested solution was provided [here](https://github.com/ambiot/ambd_arduino/issues/62#issuecomment-997225317), it didn't resolve the problem on my computer.

#### Error Message:
```plaintext
cmd /c copy /y "C:\\Users\\Chen Qizhen\\AppData\\Local\\Arduino15\\packages\\realtek\\tools\\ameba_d_tools\\1.1.2\\km0_km4_image2.bin" "C:\\Users\\Chen" "Qizhen\\AppData\\Local\\Temp\\arduino\\sketches\\DABA8B6501CFD828C2BC5D29860497F2"
The syntax of the command is incorrect.
```

#### Proposed Solution:
The error seems to be related to a syntax issue in the build process. The suggested fix in the provided solution is to modify the following line in the [platform.txt](https://github.com/ambiot/ambd_arduino/blob/5a4b8b79ede9ec2502da29b34cd89e65749bfad6/Arduino_package/hardware/platform.txt#L134) file:

Change:
```plaintext
recipe.hooks.objcopy.postobjcopy.pattern.windows=cmd /c copy /y "{runtime.tools.ameba_d_tools.path}\km0_km4_image2.bin" {build.path}
```

To:
```plaintext
recipe.hooks.objcopy.postobjcopy.pattern.windows=cmd /c copy /y "{runtime.tools.ameba_d_tools.path}\km0_km4_image2.bin" "{build.path}"
```

#### Additional Notes:
After making this modification, the issue was resolved for me, and the build process completed successfully.

**Comment by M-ichae-l** [comment]
@xixiha5230 
Thanks for point the issue out and provide a solution. Really appreciate it. Please refer to commit `785778e1bf63039ec7a4f853a79195895155b8bb` for the fix.
