### ISSUE TITLE
Expose WiFi channel in WiFi.scanNetworks() and update example to showcase usage

### ISSUE THREAD

**Issue by designer2k2** [ambiot/ambd_arduino#215]
### Hardware Environment

BW16, RTL8720DN

### Related technical area

Wifi

### Describe the ideal solution/reault/output.

The RTL8720DN provides 2,4 and 5GHz WiFi, the scanNetworks currently does not provide inside on what channel (frequency) the found SSID is.

Please add the function to provide the channel.  And expand the example to showcase on how to use it.

### Additional remarks

It would be great if the syntax stays identical to the ESP32 implemenation

### I have checked existing/closed list of issues and the Contributing Guide.

- [X]

**Comment by EstebanFuentealba** [comment]
I believe the project has been abandoned because I made an inquiry weeks ago, but there hasn't been any response. I've been testing the BW16 board, and perhaps this information could be helpful to you.

You can find the details in the following link:

https://gist.github.com/EstebanFuentealba/3da9ccecefa7e1b44d84e7cfaad2f35f

**Comment by designer2k2** [comment]
Thanks a lot @EstebanFuentealba ! Your sketch works and shows the channels! 

Do you think that this can be the base to enhance the scanNetworks function?

But i hope that this here is not abandoned...  There is so much potential in a 5GHz capable "Arduino", i am not sure why there is not more going on here.

**Comment by designer2k2** [comment]
Hello @M-ichae-l ,
until the WiFi.scanNetworks function does not show the channel, can a example be added on how to do it manually?

i took @EstebanFuentealba gist from above and made a "Advanced WiFi Scan" example from it: https://gist.github.com/designer2k2/2dc8c4a06394fdba91f3655dc9be9728

This could be added directly as a example
