### ISSUE TITLE
WS2812B fails with multiple calls to show()

### ISSUE THREAD

**Issue by lewispg228** [ambiot/ambd_arduino#241]
### Boards

SparkFun Thing Plus NORAW306

### External Hardware

No.

### Hardware Configuration

The WS2812B LED is on the PCB (as part of the design). Other than the USB-C for power/programming, no other external hardware is attached.

### Version

latest dev (checkout manually)

### IDE Name

Arduino IDE 2.3.2

### Operating System

Windows 11

### Auto Flash Mode

Enable

### Erase All Flash Memory (4MB)

Disable

### Standard Lib

Disable

### Upload Speed

921600

### Description

Fails when multiple calls to show() are used.

Note, Utilizing SPI1_PICO pin (PA_12, aka Arduino pin "14")

### Sketch

```cpp
#include "WS2812B.h"
#define NUM_OF_LEDS 1
WS2812B led(SPI1_PICO, NUM_OF_LEDS);

void setup() {
    led.begin();
}

void loop() {
  led.setPixelColor(0, 50, 0, 0);
  led.show();
  delay(500);
  led.setPixelColor(0, 0, 50, 0);
  led.show();
  delay(500);
}
```

### Error/Debug Message

```plain
No debug messages. 

The error is experienced by watching the LED fail to blink multiple colors. It get's "stuck" on the first color (red) that is set by the first time show() is called in the main loop, but then never changes after that.
```

### I have checked online documentation, FAQ, GitHub Wiki and existing/closed issues.

- [X] I confirm I have checked online documentation, FAQ, GitHub Wiki and existing/closed issues.

**Comment by M-ichae-l** [comment]
let us  discusses further if needed.
