### ISSUE TITLE
Error: Enter Uart Download Mode

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_arduino#27]
![image](https://user-images.githubusercontent.com/663460/120712532-0960c080-c4c1-11eb-95a7-e888250e9f21.png)

**Comment by M-ichae-l** [comment]
Can you explain more about how did you get this error? 
Only the picture is not helping.

**Comment by ambiot** [comment]
Please note that in order to enter the UART Download mode, 2 conditions have to be met:
1. Make sure there is no other serial terminal connecting to the serial port of Ameba
2. Press and hold the "Uart Download" button and press "Reset" button once, then release both buttons
