### ISSUE TITLE
Error using I2C

### ISSUE THREAD

**Issue by capuchino69** [ambiot/ambd_arduino#30]
I was trying to use the sth20 sensor, and did not get any answer so i tried using the I2C scanner.

Loading the scanner for i2c devices displays a list of addresses. This is the code:

     #include <Wire.h>

     void setup() {
     Wire.begin();
     
     Serial.begin(9600);
     while (!Serial); 
     Serial.println("\nI2C Scanner");
     }
     
     void loop() {
     int nDevices = 0;

    Serial.println("Scanning...");

     for (byte address = 1; address < 127; ++address) {
   
     Wire.beginTransmission(address);
     byte error = Wire.endTransmission();

      if (error == 0) {
      Serial.print("I2C device found at address 0x");
      if (address < 16) {
        Serial.print("0");
      }
      Serial.print(address, HEX);
      Serial.println("  !");

        ++nDevices;
        } else if (error == 4) {
        Serial.print("Unknown error at address 0x");
        if (address < 16) {
        Serial.print("0");
       }
       Serial.println(address, HEX);
       }
       }
       if (nDevices == 0) {
        Serial.println("No I2C devices found\n");
       } else {
        Serial.println("done\n");
       }
       delay(5000); 
       }

![image](https://user-images.githubusercontent.com/42786674/123477802-2cfcbf80-d5c4-11eb-8291-289e59a21fcc.png)

When I try to observe in the oscilloscope there is no signal, it just stays high (3.3v).

![image](https://user-images.githubusercontent.com/42786674/123479240-43a41600-d5c6-11eb-8312-0481e1ac878e.png)

**Comment by Aurical** [comment]
it is not sending anything, since there is no data to send. It would work if you add in `Wire.write(0);` after `Wire.beginTransmission(address);`
