### ISSUE TITLE
Export compiled binary

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_arduino#47]
`Warning: This core does not support exporting sketches. Please consider upgrading it or contacting its author
`

**Comment by xidameng** [comment]
You can find your compiled binaries easily at this location(Windows)
C:\Users\{USERNAME}\AppData\Local\Arduino15\packages\realtek\tools\ameba_d_tools\1.0.5

**Comment by xidameng** [comment]
There are only 3 files that matters, namely `km0_boot_all.bin`, `km4_boot_all.bin` and ` km0_km4_image2.bin`

**Comment by xidameng** [comment]
Hi @ajsb85 
A good news for you, this feature has been enabled now under the `dev` branch, and has preliminarily passed the local tests on Windows and Linux OS, if you wanna ues this feature now, simply update your `platform.txt` using the updated version here, https://github.com/ambiot/ambd_arduino/blob/dev/Arduino_package/hardware/platform.txt

**Comment by ajsb85** [comment]
I had to run the offline installation of the package and it is working properly.
BTW. I built my own custom UI desktop to flash the board.

**Comment by xidameng** [comment]
> I had to run the offline installation of the package and it is working properly.
> BTW. I built my own custom UI desktop to flash the board.

Nice!

Is it open source? Would you like to to open source it and share with the community? :)

**Comment by ajsb85** [comment]
Ok, Clever idea. I will open it.
BTW I had an issue with the dev branch.
After I build the firmware once the second build generate an issue, just fixed re-opening the IDE.
I am rolling back to the stable version.

**Comment by xidameng** [comment]
> Ok, Clever idea. I will open it.
> BTW I had an issue with the dev branch.
> After I build the firmware once the second build generate an issue, just fixed re-opening the IDE.
> I am rolling back to the stable version.

We will test the dev branch features further before merging it back to master(the stable branch now), thanks for the feedback, also open-sourcing your GUI tool 👍👍
