### ISSUE TITLE
Setting 10MHz SPI

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambd_arduino#54]
Dearest.

Can I get references of the SPI speed on Arduino?

Regards.

https://github.com/ambiot/ambd_arduino/blob/dfdc7767c2c880e344ae44cafe963478bfed4225/Arduino_package/hardware/libraries/SPI/SPI.cpp#L277-L283

**Comment by xidameng** [comment]
Hi @ajsb85 

Check these 2 lines

https://github.com/ambiot/ambd_arduino/blob/dfdc7767c2c880e344ae44cafe963478bfed4225/Arduino_package/hardware/libraries/SPI/SPI.cpp#L46

https://github.com/ambiot/ambd_arduino/blob/dfdc7767c2c880e344ae44cafe963478bfed4225/Arduino_package/hardware/libraries/SPI/SPI.cpp#L114

**Comment by ajsb85** [comment]
@xidameng thanks.

The default is 20MHz.
AmebaD support 50MHz and 25MHz.
Then for 10MHz:

SPI.beginTransaction(SPISettings(10000000, MSBFIRST, `SPI_MODE0))`


https://github.com/ambiot/ambd_arduino/blob/dfdc7767c2c880e344ae44cafe963478bfed4225/Arduino_package/hardware/libraries/SPI/SPI.cpp#L46
