### ISSUE TITLE
How disable debugging messages

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#6]
Is there a way to disable the debugging messages that get output on the serial port; for example, at startup:

    #calibration_ok:[2:19:11]

and on connecting to Wi-Fi, several messages such as:

    RTL8721D[Driver]: set group key to hw: alg:4(WEP40-1 WEP104-5 TKIP-2 AES-4) keyid

**Comment by Aurical** [comment]
the default serial port is intended for use with logging and debugging, thus the debug messages.
these messages are used when troubleshooting common wifi connection issues, and cannot be disabled by end users.
