### ISSUE TITLE
Support for Wi-Fi Soft Access Point?

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#7]
Does the RTL8722 core support creating a soft access point, like the ESP8266 or ESP32?

I can't see any commands such as **WiFi.softAP()**.

If not, are there any plans to add it?

**Comment by Aurical** [comment]
refer to AP mode example at https://www.amebaiot.com/en/amebad-arduino-ap-mode/

**Comment by technoblogy** [comment]
Thanks - found it.
