### ISSUE TITLE
Can you access SPI port 1 from the Arduino?

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#8]
The RTL8722 has two SPI ports, but I get an error if I try and use SPI1 from the Arduino IDE. Is it supported?

**Comment by Aurical** [comment]
You should be able to use SPI1 by editing 
\AppData\Local\Arduino15\packages\realtek\hardware\AmebaD\3.0.5-t03\libraries\SPI\SPI.h
and adding extern SPIClass SPI1; at the very bottom.

**Comment by ambiot** [comment]
The fix will be updated in the next release.

**Comment by M-ichae-l** [comment]
V3.0.5 fixed the issue.
