### ISSUE TITLE
The application does not end normally.

### ISSUE THREAD

**Issue by Oliver0804** [ambiot/ambd_arduino#86]
There are always ameba_image_tools running even after the Arduino is closed.

Arduino 1.8.3
macOS  12.3.1

![截圖 2022-06-06 下午8 14 52](https://user-images.githubusercontent.com/8245980/172159146-2fd1308b-f6a5-4d67-89bd-d010daaeebde.png)

**Comment by M-ichae-l** [comment]
Hi @Oliver0804 . 
I have tested it on the macOS. I did not get this issue. You can double check you device after update all your software. 

- Arduino 1.8.19
- macOS 12.4
- Activity Monitor

**Comment by ambiot** [comment]
Hi @Oliver0804 , 
Dose the issue still appear with V3.1.3 SDK? 
@M-ichae-l is not able to reproduce the issue, let us double check with the new version of SDK.

**Comment by Oliver0804** [comment]
I tested version 3.1.3 and it's good.
