### ISSUE TITLE
Reading push buttons J17 and J24

### ISSUE THREAD

**Issue by technoblogy** [ambiot/ambd_arduino#9]
Are the push buttons J17 and J24 on the RTL8722DM user readable on the input pins?

Alternatively, is there a circuit diagram of the RTL8722DM available so we could answer this sort of question ourselves?

Thanks, David

**Comment by Aurical** [comment]
you can download the board schematic at https://www.amebaiot.com/en/ameba-arduino-summary/.

**Comment by technoblogy** [comment]
Thanks!
